---
title: "WGOA-Ecopath-Rpath Model Documentation"
author: "Bia Dias"
format: html
editor: visual
---

## Code

Here we have all the code associated with the data wrangling.

## Folder structure

Scripts are separated by their main function:

```{r list_r_files}
r_files <- list.files(path = "~/WGOA-Ecopath-Rpath/code", pattern = "\\.r$", full.names = FALSE, ignore.case=TRUE)

cat(paste0("- ", r_files, collapse = "
"))
```

-   **AKFIN**:

    -   `akfin_wgoa_catch_2023.R`: This script retrieves and processes catch data from the AKFIN database for the WGOA region.

    -   `akfin_to_EwE_format_v2.R`: This script transforms the data retrieved from `akfin_wgoa_catch_2023.R` into a format suitable for Rpath.

-   **BIOENERGETICS:**

  

    -   `bioenergetic_GOA_Q10_aveRTemp_script.R`: Script to update the group names of the bioenergetic_EBS_ACLIM2_bioen.csv file #to match WGOA names.

    -   `bioenergetic_pars2.r`: Bioenergetic params for GOACLIM. Uses the "WGOA_source_data/WGOA_bioen.csv" lookup file generated by the script above. It also uses the "WGOA_source_data/species_weighted_temp_WGOA.csv" file generated by the script `WGOA_guilds_temp.`

    -   `bioenergetic_projections.r`: This script will source the `bioenergetic_pars2.r` and apply the function bioen_params() that apply the consumption modifiers and respiration modifiers.

-   **ROMS Climate Projections:**

    -   `Delta_correction.R`: Script to update the group names of the bioenergetic_EBS_ACLIM2_bioen.csv file #to match WGOA names.

    -   `ROMS_output_WGOA_EGOA.R`: Script for ROMS data collection \# <https://github.com/GOA-CLIM/ROMS_to_Index/blob/main/ROMS%20index%20generation%20example.qmd>. This script sources the delta correction function, gathers the data for the different ssps, then will extract the Biomass and Production.

        For biomass data transformation into EwE/Rpath input, filter data for depthclass "All" and NMFS_AREA 640,650 EGOA and 610-630 WGOA only.

        Carbon to wet weight conversions (B_ww_mg) can be found at:

        Table 1 (bottom explanation) from Pauly & Christensen 1995 for phytoplankton

        9: 1 ratio for the conversion of wet weight to carbon (Lockhart. A. & Cross. R. A. 1994. EMBO J. 13, 751-757)

        Table 2. from Kiorboe 2013 for the zooplankton

        Log(C mass)= a+b*log(wet mass)*

        *C_to_ww \<- 10\^((log10(value) - a) / b)*

        *Units of Cop in the* sum\* files are mg C m\^-2 of water column. Since the unit is already by area the conversion from mg*m\^-2 to mt*km\^-2 will be \*1e-3.

        The script uses the files in \~/Data/NEP_10K_revised_indices/

        to produce the files in

        ```         
          out_folder <- "WGOA_source_data/ROMSOutputWGOA"
          out_folder2 <- "wgoa_data_rpath_fitting/"
        ```

        File names example: "/Long\_", region, "*temp_monthly*", depth, ".csv"

        The final formatted time-series files are saved in `/wgoa_data_rpath_fitting/,` and detailed monthly data is saved in `/WGOA_source_data/ROMSOutputWGOA/`.

    -   `ROMS_data_transformation_anomaly.R`: is a retired code basis for the anomaly transformation that we see in `ROMS_output_WGOA_EGOA.`

-   **RACE GAP data:**

    -   `race_biomass_timeseries_var_sd_se_cv_general_code.R`: This script was written to gather race data. At the moment the full race data sets are in the googledrive. The function REEM.loadclean.RACE.googledrive() found in the `REEM_fooddata_fuctions.R` script will load the data from the googledrive and clean it.
    Here we are using
    ```
    REEM.loadclean.strata.by.stratum(strata_lookup_file    = "lookups/combined_BTS_strata.csv",
                                 stratum_bin_column    = "stratum")
    ```

    to load the strata lookup file, which is used to filter the data by stratum.
    
    For multistanza groups: One extra step is needed to calculate biomasses by juvenile and adult stages. We need the lookups/Alaska_Multistanza_GOA_vonb_2025_04_30_v2.csv file to do this. The script will use the `read.clean.csv()` function to load the VB file, which has all the information about cut-off length and growth rates for each species. The script will then use the `read.clean.csv()` function to load the strata lookup file, which is used to filter the data by stratum. The file has to be replaced to accomodate the different models.
    
    The output file will be in the `/wgoa_data_rpath_fitting/` folder, with the name _race_biomass_ts_ .csv
    This file relies on the functions from the following scripts:
    
    -   `REEM_download_functions.R`: This script contains the functions used to download the data from the ORACLE database.
    -   `REEM_fooddata_fuctions.R`: This script contains the functions used to load and clean the data from the googledrive or can be modified to load data from a local folder.
    This code sources three other scripts with functions:
        -  `GAP_get_cpue.R`
        -  `GAP_get_biomass_stratum.R`
        -  `GAP_get_cpue_guild.R`
        
    Refer to the scripts to get familiarized with the functions.
    
-   **PEDIGREE:**

    -   `pedigree_conversion_Rpath_EwE.R`: This script will read the rpath pedigree file to create a EwE pedigree file.
    

