---
title: "Lookups"
author: "Bia Dias"
format: html
editor: visual
---

## Lookups Directory

This directory contains lookup tables and scripts used to facilitate queries and data processing in the WGOA project. The lookups are essential for mapping species, gear types, and other categorical variables to their respective codes and names.

-   **RACE lookup**

    -   `lookup_table_code_WGOA_v1.R`: This script generates the lookup tables for the WGOA project. It clean the species names and maps them to the functional groups used in the model. It uses the file "*lookups/race_lookup_combined.csv*" to generate the file "*lookups/race_lookup_base_v2.csv*" used in the race codes. The script will also clean the file "*lookups/Alaska_Multistanza_GOA_vonb_2025_04_30.csv*" into the "*lookups/Alaska_Multistanza_GOA_vonb_2025_04_30_v2.csv*" file to be used in the multistanza biomass timeseries estimation from the `race_biomass_timeseries_var_sd_se_cv_general_code.R` and `race_biomass_timeseries_var_sd_se_cv.R` scripts.
    -   `Alaska_PreyLookup_MASTER.csv`: This file contains the master lookup table for prey species in the Alaska ecosystem, including their functional groups and other relevant information. It is used to map species to their respective groups in the model.This file is used for guild and diet extraction from the bottom trawl survey.
    -   `combined_BTS_strata.csv`: This file contains the combined bottom trawl survey strata information.

-   **AKFIN lookup**

    -   `model_species_for_ft_cas_akfin.csv`: This file contains functional group names for WGOA model and the species names used in the AKFIN fish ticket and CAS data.

-   **Miscellaneous lookup**

    -   `Group_Q_2021_WGOA.csv`: This file contains the QQ for most of the funtional groups in the WGOA model.

    -   `predlist_v2.csv`: This file contains the predator list used in the WGOA and EGOA models, including their functional groups and other relevant information to be used in the multstanza Biomass timeseries extraction. We no longer use this, since it was replaced by "*lookups/Alaska_Multistanza_GOA_vonb_2025_04_30_v2.csv*"
